export const SET_SAUCERS = 'SET_SAUCERS';
export const SET_PICKED_ID = 'PICKED_ID';
export const SET_CURRENT_WIN_ID = 'CURRENT_WIN_ID';
export const INCREMENT_PROGRESS = 'INCREMENT_PROGRESS';
export const DECREMENT_PROGRESS = 'DECREMENT_PROGRESS';
export const DECREMENT_ROUND = 'DECREMENT_ROUND';
export const SET_ACTIVE_ROUND = 'SET_ACTIVE_ROUND';
